import React, { useState } from "react";

const BlueprintCard = ({ blueprint }) => {
  const [isPreview, setIsPreview] = useState(false);
  if (!blueprint) return null;

  // Helper function to render different section types
  const renderSection = (section) => {
    switch (section.type) {
      case "hero":
        return (
          <section className="text-center mb-16" key={section.type}>
            <div className={`p-10 rounded-xl ${section.background ? `bg-gradient-to-br ${section.background.replace('gradient-to-br ', '')}` : 'bg-gradient-to-br from-blue-600 to-purple-700'} text-white mb-8`}>
              <h1 className="text-4xl md:text-5xl font-bold mb-4">
                {section.headline || blueprint?.title || "Generated Prototype"}
              </h1>
              <p className="text-lg md:text-xl opacity-90 max-w-2xl mx-auto mb-6">
                {section.subtext || blueprint?.description || "Your AI-generated prototype structure is ready to explore."}
              </p>
              <button className="px-8 py-3 bg-white text-blue-600 rounded-lg font-semibold shadow-lg hover:shadow-xl transition-all">
                {section.cta || "Get Started"}
              </button>
            </div>
          </section>
        );

      case "features":
        return (
          <section className="mb-16" key={section.type}>
            <h2 className="text-3xl font-bold text-gray-800 mb-8 text-center">
              {section.title || "Key Features"}
            </h2>
            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
              {section.items?.map((feature, index) => (
                <div key={index} className="p-6 bg-white rounded-xl shadow-md border border-gray-100 hover:shadow-lg transition-all">
                  {feature.icon && (
                    <div className="text-3xl mb-4">{feature.icon}</div>
                  )}
                  <h3 className="text-lg font-semibold text-gray-800 mb-2">
                    {feature.title || feature}
                  </h3>
                  {feature.description && (
                    <p className="text-gray-600 text-sm">{feature.description}</p>
                  )}
                </div>
              ))}
            </div>
          </section>
        );

      case "about":
        return (
          <section className="mb-16" key={section.type}>
            <h2 className="text-3xl font-bold text-gray-800 mb-6">
              {section.title || "About This Project"}
            </h2>
            <div className="bg-gray-50 rounded-xl p-8">
              <p className="text-gray-700 leading-relaxed text-lg">
                {section.content || "This project represents a modern website design generated by AI based on your input idea."}
              </p>
            </div>
          </section>
        );

      case "services":
        return (
          <section className="mb-16" key={section.type}>
            <h2 className="text-3xl font-bold text-gray-800 mb-8 text-center">
              {section.title || "Our Services"}
            </h2>
            <div className="grid md:grid-cols-2 gap-6">
              {section.items?.map((service, index) => (
                <div key={index} className="p-6 bg-gradient-to-br from-blue-50 to-purple-50 rounded-xl border border-blue-100">
                  <h3 className="text-xl font-semibold text-gray-800 mb-3">
                    {service.title}
                  </h3>
                  <p className="text-gray-600">{service.description}</p>
                </div>
              ))}
            </div>
          </section>
        );

      case "testimonials":
        return (
          <section className="mb-16" key={section.type}>
            <h2 className="text-3xl font-bold text-gray-800 mb-8 text-center">
              {section.title || "What Our Clients Say"}
            </h2>
            <div className="grid md:grid-cols-3 gap-6">
              {section.items?.map((testimonial, index) => (
                <div key={index} className="p-6 bg-white rounded-xl shadow-md border border-gray-100">
                  <div className="flex mb-3">
                    {[...Array(testimonial.rating || 5)].map((_, i) => (
                      <span key={i} className="text-yellow-400">⭐</span>
                    ))}
                  </div>
                  <p className="italic text-gray-600 mb-4">
                    "{testimonial.text || testimonial}"
                  </p>
                  {testimonial.author && (
                    <div>
                      <p className="font-semibold text-gray-800">{testimonial.author}</p>
                      {testimonial.role && (
                        <p className="text-sm text-gray-500">{testimonial.role}</p>
                      )}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </section>
        );

      case "footer":
        return (
          <footer className="pt-8 border-t border-gray-200 text-center" key={section.type}>
            <p className="text-gray-500 mb-4">{section.text}</p>
            {section.links && (
              <div className="flex justify-center gap-6 mb-4">
                {section.links.map((link, index) => (
                  <a key={index} href={link.url} className="text-blue-600 hover:text-blue-800 text-sm">
                    {link.text}
                  </a>
                ))}
              </div>
            )}
          </footer>
        );

      default:
        return null;
    }
  };

  return (
    <>
      {/* Main Card */}
      <div className="relative bg-white rounded-2xl shadow-xl border border-gray-100 overflow-hidden max-w-6xl mx-auto">
        {/* Toolbar */}
        <div className="flex justify-between items-center bg-gray-100 px-4 py-3 border-b border-gray-200">
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 rounded-full bg-red-400"></div>
            <div className="w-3 h-3 rounded-full bg-yellow-400"></div>
            <div className="w-3 h-3 rounded-full bg-green-400"></div>
            <span className="ml-3 text-gray-500 text-sm">
              {blueprint?.title?.toLowerCase().replace(/\s+/g, '') || 'myprotosite'}.ai
            </span>
          </div>

          <div className="flex gap-2">
            {blueprint?.design?.colorScheme && (
              <div className="flex items-center gap-1 mr-4">
                <div 
                  className="w-4 h-4 rounded-full border border-gray-300" 
                  style={{ backgroundColor: blueprint.design.colorScheme.primary }}
                ></div>
                <div 
                  className="w-4 h-4 rounded-full border border-gray-300" 
                  style={{ backgroundColor: blueprint.design.colorScheme.secondary }}
                ></div>
                <div 
                  className="w-4 h-4 rounded-full border border-gray-300" 
                  style={{ backgroundColor: blueprint.design.colorScheme.accent }}
                ></div>
              </div>
            )}
            <button
              onClick={() => setIsPreview(true)}
              className="px-4 py-1.5 bg-[#7c3aed] hover:bg-[#6d28d9] text-white text-sm rounded-lg shadow-sm transition-all"
            >
              Preview
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="bg-gradient-to-b from-gray-50 to-white p-10">
          {blueprint?.sections?.map((section) => renderSection(section))}
        </div>
      </div>

      {/* Fullscreen Preview Modal */}
      {isPreview && (
        <div className="fixed inset-0 bg-white z-50 overflow-y-auto">
          <div className="flex justify-between items-center px-6 py-4 border-b border-gray-200 sticky top-0 bg-white shadow-sm">
            <h2 className="text-lg font-semibold text-gray-800">
              Live Preview — {blueprint?.title || "Prototype"}
            </h2>
            <button
              onClick={() => setIsPreview(false)}
              className="px-4 py-1.5 bg-gray-800 hover:bg-gray-700 text-white rounded-lg text-sm transition-all"
            >
              Exit Preview
            </button>
          </div>

          <div className="max-w-7xl mx-auto">
            <div className="bg-gradient-to-b from-gray-50 to-white">
              {blueprint?.sections?.map((section) => (
                <div key={section.type} className="px-10 py-8">
                  {renderSection(section)}
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default BlueprintCard;
